spring:
  datasource:
    #    원래 꺼
    url: jdbc:h2:tcp://localhost/~/jpashop
    #    jwt테스트용
    #    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password:

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10sdf324sdfsffd2223ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 액세스 토큰 만료시간
  token-validity-in-seconds: 100000
  # 리프레시 토큰 만료시간
  refresh-token-validity-in-seconds: 1000000


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace